server:
  port: 8888
spring:
  application:
    name: erudio-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FelipeGabrill/erudio-config-server.git
          # default-label: main
          search-paths:
          - 'greeting-service*'